version: "3.3"

networks:
   glpiNet:
     ipam:
       driver: default
       config:
         - subnet: ${SUBNET}.0/24
   mariadb_mysqlNet:
     external: true

services:
  glpi:
    image: johann8/glpi:${VERSION}
    container_name: glpi
    hostname: glpi
    restart: unless-stopped
    volumes:
      - ${DOCKERDIR}/data/glpi-files:/var/www/glpi/files:rw
      - ${DOCKERDIR}/data/glpi-plugins:/var/www/glpi/plugins:rw
      - ${DOCKERDIR}/data/glpi-marketplace:/var/www/glpi/marketplace:rw
      - ${DOCKERDIR}/data/glpi-config:/var/www/glpi/config:rw
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    # Mount a temporary file system inside the container: need for systemd
    tmpfs:
      - /run
    env_file:
      - ${DOCKERDIR}/.env
    environment:
      GLPI_LANG: ${GLPI_LANG}
      TZ: ${TZ}
      MARIADB_HOST: ${MARIADB_HOST}
      MARIADB_PORT: ${MARIADB_PORT}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      VERSION: ${VERSION}
    ports:
      - ${PORT}:80
    networks:
      glpiNet:
        aliases:
          - glpi
      mariadb_mysqlNet:

#
### === MEMCACHED ===
#
  memcached:
    image: memcached:alpine3.16
    container_name: memcached
    restart: always
    depends_on:
      - glpi
    environment:
      - TZ=${TZ}
    env_file:
      - ${DOCKERDIR}/.env
    networks:
      glpiNet:
        aliases:
          - memcached

